{% set name = "credstash" %}
{% set version = "1.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c04e8734ef556ab459018da142dd0b244093ef176b3be5583e582e9a797a120

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - credstash = credstash:main

requirements:
  host:
    - python
    - pip
    - pytest >=5.4.1
  run:
    - python
    - cryptography >=2.1
    - boto3 >=1.1.1
  run_constrained:
    - pyyaml >=3.10

test:
  imports:
    - credstash
  commands:
    - pip check
    - credstash --help

about:
  home: http://github.com/fugue/credstash
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A very simple AWS based credential management and distribution system

  description: |
    CredStash is a very simple, easy to use credential management
    and distribution system that uses AWS Key Management Service(KMS)
    for key wrapping and master-key storage, and DynamoDB for credential
    storage and sharing.
  dev_url: https://github.com/fugue/credstash

extra:
  recipe-maintainers:
    - sodre
