travis:
  secure:
    BINSTAR_TOKEN: SBkr99Ndyp+8RY24og7GrEGrmp3yh2gH4gyXmkUVreR6N1Y2B58mAQqmXuF+QtZktZoJQAFwzF13fmK2Ez0PvhQyDKMFMt0YRdZOoKAvL3f0GGJ2AyZ7vSndzX0rXwLXRPfxnZ86XWZsv765zPh8xMylYOH4dTuhSlktYn5qOEj/mGXd88WUmdXp81nUz1GrlWNf/ReE/PztLH9/MKGFJiMd/Zsb4d6rnbrTGW+0hykO/z+bbX4EI4/COnRz1PcAGfs79DqF38s+dfxa3JYACEn1Z+BbYrFoP5qX8a2efVkrstuZ7K4q458dTQHOmm5GPYVgZKEpuhSqB+DrbLNr5dskoHqv+hgrBzZl9XXG17iNdH8lN1Q/NKDTtXRapKboFEjAwJbKxmwyDhEfKjZ/MFo+Vk1GCVRPzxPYYypi8oXbY8dk4P0HQmOSEWEAbzhL1HH9njemkcIactjviP6Mq2gOtHT7HXLAOrhO0H6K5+7go2Z15LNrimanccB+t0jVSGj5jQrbHkhLKHhTdSwe4MRkI7qLMqIFzZfdvjbWSgVtswib8f6TACkaCKzvhogxMG2xQYUdupW+Jk/wG+IyxxnMPgZBFACy0TIz0zfp+TnY1WiNWYsjUndU5ViiJULLwu3aBwM+nvgkFgehdNfM+kODH1JYulaU82LzDCrgNMk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
